name: notificare_push_lib
description: Official Notificare Flutter plugin. Implements the power of the Notificare platform in Flutter applications.
version: 2.2.4
homepage: https://notificare.com

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  flutter_plugin_android_lifecycle: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.4
  json_serializable: ^3.2.5

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: re.notifica.flutter
    pluginClass: NotificarePushLibPlugin
